language: python

install:
  - pip install cpplint
  - pip install pep8
  - sudo apt-get install cppcheck

script:
  - cpplint --extensions=cpp,hpp --headers=hpp $( find . -name \*.hpp -or -name \*.cpp )
  - cppcheck .
  - pep8 .
